import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

interface DirectDepositPDFData {
  employeeName: string;
  employeeEmail: string;
  bankName: string;
  routingNumber: string;
  accountNumber: string;
  accountType: string;
  employerName: string;
  employerId: string;
  payFrequency: string;
  depositAmount: string;
  depositType: string;
  formId: string;
  status: string;
  createdAt: string;
}

export async function generateDirectDepositPDF(data: DirectDepositPDFData): Promise<ArrayBuffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([612, 792]); // US Letter
  const { width, height } = page.getSize();

  const navy = rgb(0.04, 0.145, 0.25);
  const green = rgb(0, 0.83, 0.67);
  const gray = rgb(0.55, 0.55, 0.55);
  const black = rgb(0.1, 0.1, 0.1);

  // Header bar
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: navy });
  page.drawText('DepositAI', { x: 50, y: height - 45, size: 24, font: fontBold, color: green });
  page.drawText('Direct Deposit Authorization Form', { x: 50, y: height - 65, size: 11, font, color: rgb(0.9, 0.9, 0.9) });

  // Form metadata
  let y = height - 110;
  page.drawText(`Form ID: ${data.formId}`, { x: 50, y, size: 9, font, color: gray });
  page.drawText(`Status: ${data.status.toUpperCase()}`, { x: 400, y, size: 9, font: fontBold, color: data.status === 'approved' ? green : navy });
  y -= 15;
  page.drawText(`Created: ${new Date(data.createdAt).toLocaleDateString()}`, { x: 50, y, size: 9, font, color: gray });
  y -= 30;

  // Sections
  const drawSection = (title: string, fields: [string, string][], startY: number) => {
    page.drawText(title, { x: 50, y: startY, size: 12, font: fontBold, color: navy });
    page.drawRectangle({ x: 50, y: startY - 4, width: width - 100, height: 1, color: navy });

    let fy = startY - 25;
    for (const [label, value] of fields) {
      page.drawText(label + ':', { x: 60, y: fy, size: 10, font, color: gray });
      page.drawText(value || '—', { x: 200, y: fy, size: 10, font: fontBold, color: black });
      fy -= 20;
    }
    return fy - 15;
  };

  y = drawSection('Employee Information', [
    ['Name', data.employeeName],
    ['Email', data.employeeEmail],
  ], y);

  y = drawSection('Bank Account Details', [
    ['Bank Name', data.bankName],
    ['Routing Number', data.routingNumber],
    ['Account Number', data.accountNumber],
    ['Account Type', data.accountType],
  ], y);

  y = drawSection('Employer & Deposit Setup', [
    ['Employer Name', data.employerName],
    ['Employer ID', data.employerId],
    ['Pay Frequency', data.payFrequency],
    ['Deposit Type', data.depositType],
    ['Deposit Amount', data.depositAmount],
  ], y);

  // Signature line
  y -= 20;
  page.drawText('Employee Signature:', { x: 60, y, size: 10, font, color: black });
  page.drawLine({ start: { x: 200, y: y - 2 }, end: { x: 400, y: y - 2 }, thickness: 1, color: gray });
  y -= 25;
  page.drawText('Date:', { x: 60, y, size: 10, font, color: black });
  page.drawLine({ start: { x: 200, y: y - 2 }, end: { x: 300, y: y - 2 }, thickness: 1, color: gray });

  // Footer
  page.drawText('This form was generated by DepositAI · NACHA Compliant · SOC 2 Ready', {
    x: 50, y: 30, size: 8, font, color: gray,
  });
  page.drawText('© 2026 DepositAI', { x: width - 100, y: 30, size: 8, font, color: gray });

  return await pdfDoc.save();
}
